spring.datasource.url=jdbc:postgresql://ep-mute-resonance-an2zdwbu-pooler.c-6.us-east-1.aws.neon.tech:5432/trendly_dba?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_qCWfRV60NloG

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080
