# ===============================
# DATABASE CONFIG (ENV BASED)
# ===============================

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# ===============================
# JPA / HIBERNATE
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# CONNECTION POOL
# ===============================
spring.datasource.hikari.maximum-pool-size=5


# ===============================
# SERVER CONFIG (IMPORTANT FOR RENDER)
# ===============================

server.port=${PORT:8080}


# spring.profiles.active=local
